# Homework

In [8]:
import numpy as np
import pandas as pd
import matplotlib as m
import seaborn as sns

### Q1. pandas version

In [9]:
pd.__version__

'2.3.2'

In [10]:
df = pd.read_csv('file/car_fuel_efficiency.csv')
df.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

### Q2. Record count

In [11]:
len(df)

9704

### Q3. Fuel types

In [14]:
df['fuel_type'].unique()

array(['Gasoline', 'Diesel'], dtype=object)

In [13]:
df['fuel_type'].nunique()

2

### Q4. Missing values

In [24]:
df.isnull().any().sum()

np.int64(4)

### Q5. Max fuel efficiency

In [30]:
df.loc[df['origin'] == 'Asia', 'fuel_efficiency_mpg'].max()


np.float64(23.759122836520497)

### Q6. Median value of horsepower

In [38]:
median_val = df['horsepower'].median()
median_val

np.float64(149.0)

In [39]:
most_freq_val = df['horsepower'].mode()[0]
most_freq_val

np.float64(152.0)

In [41]:
df['horsepower'] = df['horsepower'].fillna(most_freq_val)

In [42]:
median_val_new = df['horsepower'].median()
median_val_new

np.float64(152.0)

### Q7. Sum of weights

In [49]:
X = np.array(df.loc[df['origin'] == 'Asia', ['vehicle_weight', 'model_year']].head(7))
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [57]:
XTX = X.T.dot(X)
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [58]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [54]:
y = [1100, 1300, 800, 900, 1000, 1100, 1200]

In [65]:
w = XTX_inv.dot(X.T).dot(y)
w.sum()

np.float64(0.5187709081074016)